apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter
  labels:
    app: converter
    project: microservices_mp4-to-mp3-converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: converter
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: converter
        project: microservices_mp4-to-mp3-converter
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: converter
          image: aniketpuro/converter-microservices1:latest
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: converter-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: converter-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          envFrom:
            - configMapRef:
                name: converter-cm
          resources:
            requests:
              cpu: "50m"
              memory: "200Mi"
            limits:
              cpu: "200m"
              memory: "400Mi"