apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - converter-deploy.yaml
  - converter-cm.yaml
  - converter-vpa.yaml

images:
  - name: aniketpuro/converter-service
    newName: aniketpuro/converter-service
    newTag: latest
