{
 "title": "QUICK HEALTH OVERVIEW",
 "tags": [
  "fast",
  "monitoring"
 ],
 "panels": [
  {
   "title": "API Gateway Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(up{app=\"gateway\"})"
    }
   ]
  },
  {
   "title": "Total RPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Error % (1m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status_code=~\"5..\"}[1m])) / sum(rate(flask_http_request_duration_seconds_count[1m])) * 100"
    }
   ]
  },
  {
   "title": "Active Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Latency Heatmap (P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(flask_http_request_duration_seconds_bucket[5m])) by (le, app))",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}