prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}

grafana:
  enabled: true
  adminPassword: admin # Change in production!
  persistence:
    enabled: true
    size: 10Gi
