apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: microservices-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [gateway, auth, converter, notification, frontend]}
  namespaceSelector:
    any: true
  endpoints:
  - port: web
    path: /metrics
    interval: 15s
