apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- notification-deploy.yaml
- notification-cm.yaml

images:
- name: aniketpuro/notification-service
  newName: aniketpuro/notification-service
  newTag: 76a719e
