prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}

grafana:
  enabled: true
  adminPassword: "admin" # Fixed password: admin
  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s/grafana/"
      serve_from_sub_path: true
    auth.anonymous:
      enabled: true
      org_name: Main Org.
      org_role: Admin
  additionalDataSources:
    - name: Prometheus
      type: prometheus
      url: http://monitoring-kube-prometheus-prometheus.monitoring.svc:9090
      access: proxy
      isDefault: true
  persistence:
    enabled: true
    size: 10Gi
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      env:
        VERIFY_SSL: "false"
    datasources:
      enabled: true
      label: grafana_datasource
      env:
        VERIFY_SSL: "false"
