---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-secret
  namespace: default
spec:
  encryptedData:
    JWT_SECRET: AgC2eSVv4B0x0YWvbvWwMvrNSx4kx03G0LqnKr/AmZbqkFf7o5h+F/D9a7e4S7fXsiHKug4Ea/NLx1NC65t+LPkm4H5J3QsyItk+cs6u+Uuqn9TNHocTGtU61iH/rK4zkFYMYbxPah2M8Z2EkzrPcTfFBKFirp4j9Bh+oQ2OdXB8Hhia+pVOW8MhwGttqaRQKv5Km2kCIJbrKJRWBoKXVYpA0mFsAGwSofgcRlFlSVePg3/E53tz1XJ1f6mJWJlcwXl8iLHuqGMsLSTy/rHgsj0cAn7DkMDtFbTLvzrsArt4GM3FVdN+3KB04sGWbFiksCAdJ6ofWzYlK1IqRVMjRChJ/ANwhwE5KrMpO/gV2NvU1k9IjSmxbFI7KFQFAQiChFsqU/j1Bbnf/7AdwK50hNsHx7oyZ2N/2XBSeeH/8Z704Ti9HVasPEtnGU0GdUXGRfcijUTpeMOMeLQIsS2nCep8BrXTyxF803nM4e5JUgq7oIyBk6cd06Kf8R97SFcEopW8rQcKDMFOCI6pobzdet24u5RnSgQFWnX5ggd+pzLNKNDoqrwsC9f7Kwtwq+7oHQDJoAyhtbd+A0Mb/l77u0BAvsy7b8+xsS3+tuIiu8pgrNM0J7La2sqqzuIFWVQ5xOaTrMAHCXoNjNa9pRUNtNcn1HZ6GiFmWjz87jFJ7LUrsY24OOzF3iPIYIETHdhAUJaX9kNLaV9J8wx0QeV16bxdcAaJJVSzoQ== # nosemgrep
  template:
    metadata:
      name: auth-secret
      namespace: default
    type: Opaque
