apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- auth-deploy.yaml
- auth-service.yaml
- auth-cm.yaml
- auth-hpa.yaml

# This will be updated by the CI pipeline
images:
- name: aniketpuro/auth-service
  newName: aniketpuro/auth-service
  newTag: 8c5e644
