apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
data:
  # The subpath where ArgoCD is hosted. Crucial for proper UI asset loading.
  server.basehref: /argocd/
  server.rootpath: /argocd
  # Required if terminating TLS at the Ingress (standard practice)
  server.insecure: "true"
