apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway 
    project: microservices_mp4-to-mp3-converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: gateway
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: gateway
          image: aniketpuro/gateway-microservices1:latest
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          envFrom:
            - configMapRef:
                name: gateway-cm
          resources:
            requests:
              cpu: "50m"
              memory: "200Mi"
            limits:
              cpu: "200m"
              memory: "400Mi"