apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway-deploy.yaml
  - gateway-service.yaml
  - gateway-cm.yaml
  - gateway-hpa.yaml

images:
  - name: aniketpuro/gateway-service
    newName: aniketpuro/gateway-service
    newTag: latest
