- name: Clone git repository
  ansible.builtin.git:
    repo: https://github.com/aniketpuro/MP3-Microservice-
    dest: "{{ ansible_facts['env']['HOME'] }}/MP3-Microservice-"
    clone: yes
    force: yes  

- name: Create all sealed secrets
  shell: |
    kubectl apply -f {{ ansible_facts['env']['HOME'] }}/MP3-Microservice-/kubernetes/secrets/

- name: Deploy rabbitmq, mysql, mongodb
  shell: |
    kubectl apply -f {{ ansible_facts['env']['HOME'] }}/MP3-Microservice-/kubernetes/manifests/{{ item }}/
  loop:
    - rabbit
    - mysql
    - mongodb

# Wait logic important hai EKS ke liye
- name: Wait for rabbitmq to be ready
  shell: "kubectl wait --for=condition=ready pod -l app=rabbitmq --timeout=300s"

- name: Make video, mp3 queue in rabbitmq
  shell: |
    kubectl exec rabbitmq-0 -- rabbitmqadmin declare queue name=video durable=true
    kubectl exec rabbitmq-0 -- rabbitmqadmin declare queue name=mp3 durable=true

- name: Deploy microservices (Auth, Notification, Converter, Gateway, Frontend)
  shell: |
    kubectl apply -k {{ ansible_facts['env']['HOME'] }}/MP3-Microservice-/kubernetes/manifests/{{ item }}/
  loop:
    - auth
    - notification
    - converter
    - gateway
    - frontend

- name: Congratulations
  debug:
    msg: "Microservices deployment complete on EKS! Repo: https://github.com/aniketpuro/MP3-Microservice-"